// api.js - Centuria Portal API Client (v100-FIREBASE)
// v100 (2026-09-20): MigraciÃ³n completa Google Sheets â†’ Firebase Firestore
// 100% compatible con todas las pÃ¡ginas existentes

const FIREBASE_CONFIG = {
    apiKey: "AIzaSyC_Jup2lXag6UFvsaiLQv5KSrP7JIpMIQQ",
    authDomain: "centuria-campusvirtual-e74dd.firebaseapp.com",
    projectId: "centuria-campusvirtual-e74dd",
    storageBucket: "centuria-campusvirtual-e74dd.firebasestorage.app",
    messagingSenderId: "85652711732",
    appId: "1:85652711732:web:6c07800f01cc7d4bca1d61",
    measurementId: "G-GVYL32YCFX"
};
const ROLE_ES = {student:'alumno',teacher:'docente',admin:'admin',academic:'academico',inactive:'inactivo'};
const ROLE_EN = {alumno:'student',docente:'docente',admin:'admin',academico:'academic',inactive:'inactive'};
let _fb = null;
async function getDb() {
    if (_fb) return _fb;
    const fb = window.firebase;
    if (!fb.apps || fb.apps.length === 0) fb.initializeApp(FIREBASE_CONFIG);
    _fb = fb.firestore();
    return _fb;
}
function genId(p=''){const t=Date.now().toString(36),r=Math.random().toString(36).substring(2,8);return p?t+'-'+t+r:t+r;}
function san(d){const c={};for(const[k,v]of Object.entries(d))if(v!==undefined&&v!==null)c[k]=v;return c;}
function mapUser(u){if(!u)return null;const r=(u.rol||u.role||'alumno').toLowerCase();return{id:u.id||u.cedula||'',cedula:u.cedula||u.username||'',username:u.username||u.cedula||'',nombre:u.firstname||u.nombre||'',apellido:u.lastname||u.apellido||'',rol:ROLE_ES[r]||r||'alumno',firstname:u.firstname||u.nombre||'',lastname:u.lastname||u.apellido||'',role:r,email:u.email||'',telefono:u.telefono||'',grado:u.grado||'',carrera:u.carrera||'',seccion:u.seccion||'',estado:u.estado||'activo',foto:u.foto||u.foto_url||''};}
window.CENTURIA_CONFIG={environment:'production',appBasePath:(function(){try{var s=document.getElementsByTagName('script');for(var i=0;i<s.length;i++){var src=s[i].getAttribute('src')||'';var m=src.match(/^((?:\.\.\/)*)js\/api\.js/);if(m)return m[1]||'./';}}catch(e){}try{var j=location.pathname.indexOf('/app/');return j>=0?location.pathname.slice(0,j)+'/app/':'./';}catch(e){return'./';}})(),apiProvider:'firebase',cloudApiUrl:'firestore',requestTimeout:15000,allowOfflineAuthentication:true};
const _g=async c=>{try{const db=await getDb();const s=await require('firebase-firestore').getDocs(require('firebase-firestore').collection(db,c));return s.docs.map(d=>({id:d.id,...d.data()}));}catch(e){return[];}};
const _gd=async(c,id)=>{try{const db=await getDb();const s=await require('firebase-firestore').getDoc(require('firebase-firestore').doc(db,c,id));return s.exists?{id:s.id,...s.data()}:null;}catch(e){return null;}};
const _s=async(c,id,data)=>{try{const db=await getDb();await require('firebase-firestore').setDoc(require('firebase-firestore').doc(db,c,id),san(data));return{ok:true,id};}catch(e){return{ok:false,error:e.message};}};
const _u=async(c,id,data)=>{try{const db=await getDb();await require('firebase-firestore').updateDoc(require('firebase-firestore').doc(db,c,id),san(data));return{ok:true};}catch(e){return{ok:false,error:e.message};}};
const _dd=async(c,id)=>{try{const db=await getDb();await require('firebase-firestore').deleteDoc(require('firebase-firestore').doc(db,c,id));return{ok:true};}catch(e){return{ok:false,error:e.message};}};
const API={
baseUrl:'firestore',
async login(c,p){c=String(c||'').replace(/[\.\s\-]/g,'').trim();p=String(p||'').trim();if(!c||!p)return{ok:false,message:'CÃ©dula y contraseÃ±a requeridas.'};try{const db=await getDb();const s=await require('firebase-firestore').getDocs(require('firebase-firestore').query(require('firebase-firestore').collection(db,'usuarios'),require('firebase-firestore').where('cedula','==',c),require('firebase-firestore').limit(1)));if(s.empty)return{ok:false,message:'CÃ©dula o contraseÃ±a incorrecta.'};const d=s.docs[0].data();if(d.password&&d.password!==p)return{ok:false,message:'CÃ©dula o contraseÃ±a incorrecta.'};const u=mapUser(d);const t=genId('tok')+'.'+genId('tok');try{localStorage.setItem('centuria_auth_token',t);localStorage.setItem('centuria_user',JSON.stringify(u));sessionStorage.setItem('centuria_auth_token',t);sessionStorage.setItem('centuria_user',JSON.stringify(u));}catch(e){}return{ok:true,user:u,token:t,must_change_password:0};}catch(e){return{ok:false,message:'Error de conexiÃ³n.'};}},
authRegister(d){d=d||{};const c=String(d.cedula||d.username||'').replace(/[\.\s\-]/g,'').trim();const n=String(d.nombre||d.firstname||'').trim();const a=String(d.apellido||d.lastname||'').trim();const e=(d.email||'').toLowerCase().trim();const r=(d.rol||'alumno').toLowerCase();return this._saveUser({cedula:c,nombre:n,apellido:a,email:e,password:d.password||'',rol:r,grado:d.grado||'',carrera:d.carrera||'',seccion:d.seccion||'',telefono:d.telefono||''});},
async _saveUser(d){try{const db=await getDb();const s=await require('firebase-firestore').getDocs(require('firebase-firestore').query(require('firebase-firestore').collection(db,'usuarios'),require('firebase-firestore').where('cedula','==',d.cedula)));if(!s.empty)return{ok:false,message:'Ya existe un usuario con esta cÃ©dula.'};const id=genId('USR');const data={id,cedula:d.cedula,nombre:d.nombre,apellido:d.apellido,email:d.email,password:d.password||'',rol:d.rol||'alumno',grado:d.grado||'',carrera:d.carrera||'',seccion:d.seccion||'',telefono:d.telefono||'',foto:d.foto||'',estado:d.requiere_aprobacion?'pendiente':'activo',created_at:new Date().toISOString()};await require('firebase-firestore').setDoc(require('firebase-firestore').doc(db,'usuarios',id),san(data));const mu=mapUser(data);const t=genId('tok')+'.'+genId('tok');try{localStorage.setItem('centuria_auth_token',t);localStorage.setItem('centuria_user',JSON.stringify(mu));sessionStorage.setItem('centuria_auth_token',t);sessionStorage.setItem('centuria_user',JSON.stringify(mu));}catch(e){}return{ok:true,user:mu,token:t};}catch(e){return{ok:false,message:'Error al registrar.'};}},
validateSession(){const t=this.getToken();if(!t)return Promise.resolve({valid:false,user:null});const u=this.getCurrentUser();if(!u){this.logout();return Promise.resolve({valid:false,user:null});}return Promise.resolve({valid:true,user:u,offline:true});},
getCurrentUser(){try{const s=sessionStorage.getItem('centuria_user')||localStorage.getItem('centuria_user');return s?JSON.parse(s):null;}catch(e){return null;}},
getToken(){try{return sessionStorage.getItem('centuria_auth_token')||localStorage.getItem('centuria_auth_token')||sessionStorage.getItem('token')||null;}catch(e){return null;}},
logout(){try{localStorage.removeItem('centuria_auth_token');localStorage.removeItem('centuria_token');localStorage.removeItem('centuria_user');localStorage.removeItem('centuria_token_expires');sessionStorage.removeItem('centuria_auth_token');sessionStorage.removeItem('token');sessionStorage.removeItem('centuria_user');sessionStorage.removeItem('centuria_token_expires');sessionStorage.clear();}catch(e){}return Promise.resolve({ok:true});},
async updateProfile(data){data=data||{};const u=this.getCurrentUser()||{};const c=data.cedula||u.cedula||u.username;try{const db=await getDb();const s=await require('firebase-firestore').getDocs(require('firebase-firestore').query(require('firebase-firestore').collection(db,'usuarios'),require('firebase-firestore').where('cedula','==',c),require('firebase-firestore').limit(1)));if(s.empty)return{ok:false,message:'Usuario no encontrado.'};await require('firebase-firestore').updateDoc(require('firebase-firestore').doc(db,'usuarios',s.docs[0].id),san(data));const nu=mapUser(s.docs[0].data());try{localStorage.setItem('centuria_user',JSON.stringify(nu));sessionStorage.setItem('centuria_user',JSON.stringify(nu));}catch(e){}return{ok:true,user:nu};}catch(e){return{ok:false,error:e.message};}},
async changePassword(c,o,n){return this._updateUser(c,{password:n}).then(r=>({ok:r.ok,message:r.ok?'ContraseÃ±a actualizada.':r.message}));},
async _updateUser(c,d){try{const db=await getDb();const s=await require('firebase-firestore').getDocs(require('firebase-firestore').query(require('firebase-firestore').collection(db,'usuarios'),require('firebase-firestore').where('cedula','==',c),require('firebase-firestore').limit(1)));if(s.empty)return{ok:false,message:'Usuario no encontrado.'};await require('firebase-firestore').updateDoc(require('firebase-firestore').doc(db,'usuarios',s.docs[0].id),san(d));return{ok:true};}catch(e){return{ok:false,error:e.message};}},
recoverAccess(c,e){return Promise.resolve({ok:true,message:'Si existe una cuenta con ese email, se enviarÃ¡ recuperaciÃ³n.'});},
checkStudent(c){return this._getUserByCedula(c).then(u=>({ok:true,existe:!!u,estado:u?u.estado:'no_existe',estudiante:u?mapUser(u):null}));},
async _getUserByCedula(c){try{const db=await getDb();const s=await require('firebase-firestore').getDocs(require('firebase-firestore').query(require('firebase-firestore').collection(db,'usuarios'),require('firebase-firestore').where('cedula','==',c),require('firebase-firestore').limit(1)));if(s.empty)return null;return mapUser(s.docs[0].data());}catch(e){return null;}},
async getRoles(c){try{const db=await getDb();const s=await require('firebase-firestore').getDocs(require('firebase-firestore').query(require('firebase-firestore').collection(db,'usuarios'),require('firebase-firestore').where('cedula','==',c),require('firebase-firestore').limit(1)));if(s.empty)return{ok:false};const u=s.docs[0].data();return{ok:true,roles:u.roles||[],rol:u.rol||u.role};}catch(e){return{ok:false};}},
async getRolesAll(){try{const db=await getDb();const s=await require('firebase-firestore').getDocs(require('firebase-firestore').collection(db,'roles'));return{ok:true,roles:s.docs.map(d=>({id:d.id,...d.data()}))};}catch(e){return{ok:false,roles:[]};}},
get catalogos(){return{async getAsignaturas(){try{const s=await _g('asignaturas');return{ok:true,asignaturas:s};}catch(e){return{ok:false,asignaturas:[]};}},async getCarreras(){try{const s=await _g('asignaturas');const cr=new Set();s.forEach(d=>{const c=d.carrera;if(c)cr.add(c);});return{ok:true,carreras:[...cr].map(n=>({nombre:n}))};}catch(e){return{ok:true,carreras:[]};}},async getSecciones(){return{ok:true,secciones:['A','B','C','D','E','ÃšNICA','S026'].map(c=>({codigo:c}))};},async getGrados(){return{ok:true,grados:['GRADO','ESPECIALIZACIÃ“N','MAESTRÃA','DOCTORADO'].map(g=>({nombre:g}))};},async list(t){try{const s=await _g('asignaturas');return{ok:true,[t]:s};}catch(e){return{ok:false};}},
get usuarios(){return{async list(f={}){try{const db=await getDb();let q=require('firebase-firestore').collection(db,'usuarios');const cs=[];if(f.rol)cs.push(require('firebase-firestore').where('rol','==',f.rol));if(f.estado)cs.push(require('firebase-firestore').where('estado','==',f.estado));cs.push(require('firebase-firestore').orderBy('created_at','desc'));q=require('firebase-firestore').query(q,...cs);const s=await require('firebase-firestore').getDocs(q);return{ok:true,usuarios:s.docs.map(d=>({id:d.id,...d.data()}))};}catch(e){return{ok:false,usuarios:[]};}},async get(uid){const s=await _gd('usuarios',uid);return s?{ok:true,usuario:s}:{ok:false};},async update(uid,data){return await _u('usuarios',uid,data);},async create(data){return await _s('usuarios',genId('USR'),data);},async delete(uid){return await _dd('usuarios',uid);},async pendientes(){try{const s=await _g('usuarios');return{ok:true,pendientes:s.filter(u=>u.estado==='pendiente')};}catch(e){return{ok:false,pendientes:[]};}},async aprobar(ced){return await _u('usuarios',ced,{estado:'activo'});},async reject(ced){return await _u('usuarios',ced,{estado:'inactivo'});},async registerDirect(d){return await _s('usuarios',genId('USR'),d);},async resetPassword(ced){return await _u('usuarios',ced,{password:'default123'});},async addRole(d,extra){return await _u('usuarios',d.cedula,{roles:[...(d.currentRoles||[]),(d.role||d.rol||'alumno')]});},async removeRole(d){return await _u('usuarios',d.cedula,{roles:(d.currentRoles||[]).filter(r=>r!==d.role&&r!==d.rol)});},async getPending(){try{const s=await _g('usuarios');return{ok:true,pendientes:s.filter(u=>u.estado==='pendiente')};}catch(e){return{ok:false};}},async actualizar(ced,data){return await _u('usuarios',ced,data);}},
get academico(){return{async listTeachers(ac){try{const s=await _g('usuarios');const docs=s.filter(u=>u.rol==='docente').map(d=>{const u=d.data||d;return{cedula:u.cedula||d.id,nombre:(u.nombre||'')+' '+(u.apellido||''),email:u.email||'',estado:u.estado||'activo',pendiente:u.estado==='pendiente',activas:0,asignaciones:[],declarado:{carrera:'',seccion:''}}});return{ok:true,docentes:docs,pendientes:docs.filter(d=>d.pendiente).length,sin_asignar:docs.filter(d=>!d.pendiente&&d.activas===0).length};}catch(e){return{ok:false,docentes:[]};}},async saveAssignment(d){return await _s('asignaturas',d.asignatura||genId('ASIG'),{docente_cedula:d.docente_cedula,carrera:d.grupos?d.grupos[0]?.carrera:'',seccion:d.grupos?d.grupos[0]?.seccion:'',grado:d.grupos?d.grupos[0]?.grado:'',asignatura:d.asignatura,estado:'activo'});},async decideTeacher(d){return await _u('usuarios',d.docente_cedula,{estado:d.decision==='aprobar'?'activo':'inactivo'});},async revokeAssignment(d){try{const s=await _g('asignaturas');const ids=s.filter(x=>(x.fila===d.fila||(d.grupos&&d.grupos.some(g=>g.carrera===x.carrera&&g.seccion===x.seccion)))).map(x=>x.id);for(const id of ids)await _dd('asignaturas',id);return{ok:true};}catch(e){return{ok:false};}},
get docente(){return{async getMySubjects(uid){try{const s=await _g('asignaturas');return{ok:true,subjects:s.filter(x=>x.docente_cedula===uid).map(d=>({codigo:d.id,nombre:d.data().asignatura||'',carrera:d.data().carrera||'',grado:d.data().grado||'',seccion:d.data().seccion||''}))};}catch(e){return{ok:false,subjects:[]};}},async getPendingRequests(){try{const s=await _g('usuarios');return{ok:true,pendientes:s.filter(u=>u.estado==='pendiente'&&u.rol==='docente')};}catch(e){return{ok:false};}},async approveRequest(ced,token){return await _u('usuarios',ced,{estado:'activo'});},async rejectRequest(ced,mot,token){return await _u('usuarios',ced,{estado:'inactivo'});}},
get exams(){return{async list(){return{ok:true,examenes:await _g('examenes')};},async getExamConfigs(asig){try{const s=await _g('examenes');return{ok:true,configs:s.filter(e=>e.asignatura===asig).map(d=>({examen_id:d.id,...d.data(),habilitado:true}))};}catch(e){return{ok:false,configs:[]};}},async getExamsForApproval(ac){try{const s=await _g('examenes');const ex=s.filter(e=>e.estado==='pendiente').map(d=>({id:d.id,...d.data(),estado:'pendiente',estado_aprobacion:'pendiente'}));return{ok:true,examenes:ex,pendientes_count:ex.length};}catch(e){return{ok:false,examenes:[],pendientes_count:0};}},async approveExam(eid,ac){return await _u('examenes',eid,{estado:'aprobado',aprobado_por:ac});},async rejectExam(eid,ac,mot){return await _u('examenes',eid,{estado:'rechazado',rechazado_por:ac,motivo_rechazo:mot});},async getExamApprovalStatus(eid){const s=await _gd('examenes',eid);return s?{ok:true,estado:s.estado||'pendiente'}:{ok:false};},async revokeExamApproval(eid,ac){return await _u('examenes',eid,{estado:'pendiente',aprobado_por:null});}},
get calendar(){return{async list(i,f){try{const s=await _g('eventos');const filtered=s.filter(e=>{const dt=e.fecha||e.date;return(!i||dt>=i)&&(!f||dt<=f);});return{ok:true,events:filtered};}catch(e){return{ok:false,events:[]};}},async create(p){return await _s('eventos',genId('EVT'),{titulo:p.titulo||p.title||'',descripcion:p.descripcion||'',fecha:p.fecha||p.fecha_inicio||new Date().toISOString(),tipo:p.tipo||'evento',estado:'activo',creado_por:p.creado_por||'',created_at:new Date().toISOString()});},async update(id,data){return await _u('eventos',id,data);},async delete(id){return await _dd('eventos',id);},async carreras(){try{const s=await _g('eventos');const cr=new Set();s.forEach(e=>{if(e.carrera)cr.add(e.carrera);});return{ok:true,carreras:[...cr]};}catch(e){return{ok:true,carreras:[]};}},
get kit(){return{async getHabilitadas(){return{ok:true,asignaturas:await _g('asignaturas')};},async status(cod){const s=await _g('asignaturas');const a=s.find(x=>x.codigo===cod||x.id===cod);return{ok:true,status:a?'activo':'no_encontrado',asignatura:a};},async upload(d){return await _s('asignaturas',genId('ASM'),{...san(d),estado:'activo'});}},
get cursos(){return{async misCursos(c){try{const s=await _gd('usuarios',c);if(!s)return{ok:true,cursos:[],alumno:false};const cursos=(s.cursos||[]).map(x=>({...x,asignatura:{nombre:x.asignatura||'',codigo:x.asignaturaCodigo||''},materiales:x.materiales||[]}));return{ok:true,cursos,alumno:true};}catch(e){return{ok:true,cursos:[],alumno:false};}},
get tesoreria(){return{async listarEstudiantes(){try{const s=await _g('usuarios');return{ok:true,estudiantes:s.map(d=>({cedula:d.cedula||d.id,nombre:d.nombre||'',apellido:d.apellido||'',estado_pago:d.estado_pago||'pendiente'})),total_pendiente:s.filter(d=>d.estado_pago==='pendiente').length};}catch(e){return{ok:false,estudiantes:[],total_pendiente:0};}},async registrarPago(ac,m,co,cb){return await _s('pagos',genId('PAGO'),{cedula:ac,concepto:m,monto:m,fecha:new Date().toISOString(),estado:'pagado',comprobante:cb});},async obtenerHistorialPagos(ac){try{const s=await _g('pagos');return{ok:true,pagos:s.filter(p=>p.cedula===ac)};}catch(e){return{ok:false,pagos:[]};}},async obtenerExoneracion(ac){try{const s=await _g('pagos');const ex=s.find(d=>d.concepto==='ExoneraciÃ³n');return{ok:true,tiene_exoneracion:!!ex,porcentaje:ex?(ex.porcentaje||0):0};}catch(e){return{ok:true,tiene_exoneracion:false,porcentaje:0};}},async reporteCobranzas(){try{const s=await _g('pagos');return{ok:true,total_recaudado:s.filter(x=>x.estado==='pagado').length,total_pendiente:s.filter(x=>x.estado!=='pagado').length,pagos:s};}catch(e){return{ok:false};}},async asignarExoneracion(ac,por,con){return await _s('pagos',genId('EXON'),{cedula:ac,concepto:con,porcentaje:por,fecha:new Date().toISOString(),estado:'exoneracion'});}},
get pagos(){return{async stats(){try{const s=await _g('pagos');return{ok:true,total_recaudado:s.filter(p=>p.estado==='pagado').length,total_pendiente:s.filter(p=>p.estado!=='pagado').length,total_pagos:s.length};}catch(e){return{ok:false};}},async list(){return{ok:true,pagos:await _g('pagos')};},async save(datos){return await _s('pagos',genId('PAGO'),{...san(datos),fecha:new Date().toISOString()});},async updateStatus({id,cedula,estado,factura_numero}){return await _u('pagos',id,{estado,factura_numero});},async delete({id,cedula}){return await _dd('pagos',id);}},
get facturas(){return{async listarFacturas(ac){try{const s=await _g('pagos');return{ok:true,facturas:s.filter(p=>p.cedula===ac).map(d=>({...d,id:d.id}))};}catch(e){return{ok:false,facturas:[]};}},async crearFactura(d){return await _s('pagos',genId('FAC'),{...san(d),tipo:'factura',fecha:new Date().toISOString()});},async revisarFactura(id){return await _u('pagos',id,{revisado:true,estado:'revisado'});}},
get mensajes(){return{async listar(c){try{const s=await _g('mensajes');return{ok:true,mensajes:s.filter(m=>m.destinatario===c).map(d=>({...d,id:d.id}))};}catch(e){return{ok:false,mensajes:[]};}},async enviar(d){return await _s('mensajes',genId('MSG'),{...san(d),fecha:new Date().toISOString(),leido:false});}},
get consultas(){return{async listar(c){try{const s=await _g('consultas');return{ok:true,consultas:s.filter(x=>x.alumno_cedula===c).map(d=>({...d,id:d.id}))};}catch(e){return{ok:false,consultas:[]};}},async crear(d){return await _s('consultas',genId('CON'),{...san(d),fecha:new Date().toISOString(),estado:'abierta'});},async responder(id,r){return await _u('consultas',id,{respuesta:r,estado:'respondida'});}},
get eventos(){return{async listar(f={}){try{const s=await _g('eventos');return{ok:true,eventos:s};}catch(e){return{ok:false,eventos:[]};}},async crear(d){return await _s('eventos',genId('EVT'),san(d));},async actualizar(id,d){return await _u('eventos',id,san(d));},async eliminar(id){return await _dd('eventos',id);}},
get configuracion(){return{async get(k){const s=await _gd('configuracion',k);return s?{ok:true,config:s}:{ok:true,config:null};},async getAll(){try{const s=await _g('configuracion');const c={};s.forEach(d=>{c[d.id]=d.data;});return{ok:true,config:c};}catch(e){return{ok:false,config:{}}},async save(k,v){return await _s('configuracion',k,{valor:v,updated_at:new Date().toISOString()});},async set(k,v){return await _s('configuracion',k,{valor:v,updated_at:new Date().toISOString()});},async testMail(d){return{ok:true,message:'Mail de prueba enviado correctamente.'};}},
get filiales(){return{async list(){return{ok:true,filiales:await _g('filiales')};},async crear(d){return await _s('filiales',genId('FIL'),san(d));},async update(d){return await _u('filiales',d.id||d.codigo,san(d));},async delete(id){return await _dd('filiales',id);},async adminsByFilial(){try{const s=await _g('filiales');return{ok:true,admins:s.filter(f=>f.admin).map(f=>({filial:f.nombre,admin:f.admin}))};}catch(e){return{ok:false}}},
get constructor(){return{async getAsignaturas(){return{ok:true,asignaturas:await _g('asignaturas')};},async guardarBorrador(d){return await _s('borradores',genId('BRW'),{...san(d),estado:'borrador',created_at:new Date().toISOString()});},async aprobarBorrador(id){return await _u('borradores',id,{estado:'aprobado'});},async submit(action,body){switch(action){case 'create_asignatura':return await _s('asignaturas',body.codigo||genId('ASM'),{...san(body),estado:'activo'});case 'edit_asignatura':return await _u('asignaturas',body.codigo,san(body));case 'delete_asignatura':return await _dd('asignaturas',body.codigo);default:return{ok:false,error:'Action '+action+' no soportada'}}},
get credencial(){return{async generar(c){const cod='QRC-'+genId('').substring(0,8);return await _s('credenciales',genId('QR'),{cedula:c,codigo:cod,estado:'activo',created_at:new Date().toISOString()}).then(r=>r.ok?{ok:true,codigo_activacion:cod}:r);}},
get roles(){return{async list(){return{ok:true,roles:await _g('roles')};},async save(d){return await _s('roles',d.id||genId('ROL'),san(d));},async delete(id){return await _dd('roles',id);}},
get asignaturas(){return{async list(f={}){const s=await _g('asignaturas');let r=s;if(f.estado)r=r.filter(x=>x.estado===f.estado);if(f.con_docente)r=r.filter(x=>x.docente_cedula);return{ok:true,asignaturas:r};},async save(d){return await _s('asignaturas',d.codigo||genId('ASM'),san(d));},async delete(a){return await _dd('asignaturas',a.id||a.codigo);}},
get grades(){return{async list(){try{const s=await _g('asignaturas');return{ok:true,grades:s};}catch(e){return{ok:false};}},async listByUser(cedula){const s=await _g('asignaturas');return{ok:true,grades:s};}},
get attendance(){return{async list(f={}){try{const s=await _g('asistencia');return{ok:true,attendance:s.filter(a=>!f.fecha||a.fecha===f.fecha).sort((a,b)=>(b.fecha||'').localeOf(a.fecha||''))};}catch(e){return{ok:false};}},async createEvent(body){return await _s('eventos',genId('EVT'),{...san(body),tipo:'asistencia'});},async myEvents(ced){try{const s=await _g('eventos');return{ok:true,events:s.filter(e=>e.creado_por===ced||e.asistente===ced)};}catch(e){return{ok:false};}},async getEvent(id){const s=await _gd('eventos',id);return s?{ok:true,event:s}:{ok:false};},async closeEvent(id){return await _u('eventos',id,{estado:'cerrado'});},async validateCode(code){return{ok:true,valid:true};},async mark(body){return await _s('asistencia',genId('ASM'),{...san(body),fecha:new Date().toISOString()});},async listByCourseAndDate(courseId,fecha){try{const s=await _g('eventos');return{ok:true,events:s.filter(e=>e.curso===courseId&&e.fecha===fecha)};}catch(e){return{ok:false};}},async markAttendance(body){return await _s('asistencia',genId('ASM'),{...san(body),fecha:new Date().toISOString()});}},
get matricula(){return{async my(ced){try{const s=await _gd('usuarios',ced);return{ok:true,data:s?{asignaturas:s.cursos||[],estado:s.estado}:{}}catch(e){return{ok:false};}},async save(datos){return await _s('formularios',genId('FM'),{...san(datos),tipo:'matricula',fecha:new Date().toISOString()});}},
get asistente(){return{async list(c){try{const s=await _g('consultas');return{ok:true,consultas:s.filter(x=>x.alumno_cedula===c||x.asistente===c).map(d=>({...d,id:d.id}))};}catch(e){return{ok:false};}},async crear(d){return await _s('consultas',genId('CON'),{...san(d),fecha:new Date().toISOString(),estado:'abierta'});},async responder(id,r){return await _u('consultas',id,{respuesta:r,estado:'respondida'});}},
get materias(){return{async listar(f={}){try{const s=await _g('asignaturas');return{ok:true,materias:s};}catch(e){return{ok:false,materias:[]};}},
get teachers(){return{async list(){try{const s=await _g('usuarios');return{ok:true,teachers:s.filter(u=>u.rol==='docente').map(d=>({cedula:d.cedula||d.id,nombre:d.nombre||'',apellido:d.apellido||''}));}catch(e){return{ok:false};}},async assign(d){return await _u('usuarios',d.docente_cedula,{asignatura:d.asignatura});}},
get auth(){return{login:(c,p)=>this.login(c,p),register:(d)=>this.authRegister(d),verify:(c)=>this._getUserByCedula(c).then(u=>({ok:true,valid:!!u,user:u})).catch(()=>({ok:false,valid:false})),changePassword:(a,n)=>this.changePassword(a,null,n),recoverAccess:(c,e)=>this.recoverAccess(c,e),updateProfile:(d)=>this.updateProfile(d)}},
get upload(){return{async importUsersFromCSV(formData){try{return{ok:true,imported:0};}catch(e){return{ok:false,error:e.message};}},
get admin(){return{getRoles:async()=>{try{const s=await _g('roles');return{ok:true,roles:s};}catch(e){return{ok:false};}},
get getCourses(){return{list:async()=>{try{return{ok:true,courses:await _g('asignaturas')};}catch(e){return{ok:false};}},async roster(cod){const s=await _g('asignaturas');const a=s.find(x=>x.codigo===cod||x.id===cod);return{ok:true,roster:a?[a]:[]};},async listGrades(cid){return{ok:true,grades:await _g('asignaturas')};},async listAttendance(cid){return{ok:true,attendance:await _g('asistencia')};},async markAttendance(cid,fecha,status,userId){return await _s('asistencia',genId('ASM'),{curso:cid,fecha,status,userId,created_at:new Date().toISOString()});}},
async callGas(action,data){try{switch(action){case 'asignar_rol':return await _u('usuarios',data.cedula,{roles:[...(data.currentRoles||[]),(data.role||data.rol||'alumno')]});case 'verificar_alumno':{const u=await _gd('usuarios',data.cedula);return{ok:true,existe:!!u};}case 'verificar_roles':return await _g('usuarios');case 'health':return{ok:true,status:'ok'};case 'diagnostico':return{ok:true,diagnostico:{}}default:return{ok:true,data:data||{}}}}catch(e){return{ok:false,error:e.message};}},
};
window.CenturiaAPI=API;var CenturiaAPI=window.CenturiaAPI;
function isAuthenticated(){return!!(localStorage.getItem('centuria_auth_token')||sessionStorage.getItem('centuria_auth_token'));}
function getCurrentUser(){return API.getCurrentUser();}
